# Generated by Django 2.2.4 on 2019-09-01 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_name', models.CharField(max_length=150)),
                ('lead_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_phone', models.CharField(max_length=20)),
                ('campaign_remarks', models.TextField(blank=True, null=True)),
                ('enquired_for', models.CharField(blank=True, max_length=250, null=True)),
                ('counselor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('leadclose', 'Lead Closed'), ('leadwalkin', 'Lead walked in'), ('leadfollowup', 'Leads follow up'), ('walkinfollowup', 'Walk in follow up'), ('walkinreg', 'Walk in registered'), ('walkinclose', 'Walk in closed')], default='', max_length=200, null=True)),
                ('Year_of_passing', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2019, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('final_report', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_counseled', models.BooleanField(default=False)),
                ('generation_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeadRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_remarks', to='leads.Lead')),
            ],
        ),
    ]
