# Generated by Django 2.2.4 on 2019-09-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails', models.IntegerField(blank=True, default=0, null=True)),
                ('messages', models.IntegerField(blank=True, default=0, null=True)),
                ('calls', models.IntegerField(blank=True, default=0, null=True)),
                ('online_submissions', models.IntegerField(blank=True, default=0, null=True)),
                ('follow_ups', models.IntegerField(blank=True, default=0, null=True)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
