# Generated by Django 2.2.4 on 2019-09-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190905_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprecord',
            name='submitted_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
